### ISSUE TITLE
Build breakage due to pytest-runner requirement as setup_requires

### ISSUE THREAD

**Issue by yegorich** [thombashi/DataProperty#19]
I'm integrating DataProperty into Buildroot (embedded Linus distro).  Buildroot has no testing facility for Python packages hence this line [1] breaks build process [2]. Could you remove this requirement? This the first time I see this in a setup.py file. Can it be moved to requirements/test_requirements.txt?

[1] https://github.com/thombashi/DataProperty/blob/master/setup.py#L41
[2] http://autobuild.buildroot.net/results/0c8/0c8e0ceccc2d5f48138ec4f95e57729e33108f59/build-end.log

Thanks

**Comment by thombashi** [comment]
I'm sorry for the inconvenience. Now, I merged you pull request #20, and updated the DataProperty package to 3.1 on PyPI. Is this package solves your problem?

**Comment by yegorich** [comment]
Thanks for making a new release. I'll bump package's version in Buildroot and let you know, if the error has gone.

**Comment by yegorich** [comment]
@thombashi with version 0.3.1 the builds are successful. You can apply this patch to other projects. Thanks.

**Comment by thombashi** [comment]
@yegorich Thank you for the report. I will apply this patch to other projects which have the same problem.

**Comment by yegorich** [comment]
For now am mostly interested in pathvalidate and pytablewriter.

**Comment by thombashi** [comment]
Sure. I will fix these two packages with high priority.
However, it would be at this weekend, I can't touch with my environment until that.

**Comment by yegorich** [comment]
Thanks. Will integrate new versions in Buildroot. Are these your contributions? https://www.openhub.net/p/727521/contributors/3124681050612350 
Care to create an account there?

**Comment by thombashi** [comment]
I've created an account on Open Hub.
https://www.openhub.net/accounts/thombashi
:simple_smile:
