### ISSUE TITLE
Stop changing the default decimal precision globally

### ISSUE THREAD

**Issue by benjaminrigaud** [thombashi/DataProperty#59]
Hi,

in https://github.com/thombashi/DataProperty/blob/master/dataproperty/_function.py#L13
The decimal context is modified and the default precision is changed to 60.

It changes the global decimal behavior of any code importing your library.

**Comment by thombashi** [comment]
@benjaminrigaud 
Thank you for your report.
This problem has been fixed in `DataProperty 1.0.2`.
